### ISSUE TITLE
Changing the limit for POST body size

### ISSUE THREAD

**Issue by kenota** [postgraphql/postgraphql#372]
I am using postgraphql exposed Postgres function to process quite a bit amount of data (not storing binary files in db, use case is providing array of objects to db to process), and I have encountered following error reply when doing POST:

`{"errors":[{"message":"request entity too large"}]}`

It seems that I am hitting default limit of express post body parsing middleware which can be easily changed in code. 

Just wanted to check if postgraphql exposing an option/way to configure this which is not mentioned in doc? 

If not, I assume the best solution to use postgraphql as a library in custom small nodejs/express server?

**Comment by calebmer** [comment]
We may want to discuss raising the default, otherwise I’m totally open to adding this option 👍

It looks like @guyemerson referenced this PR in a commit to his fork: https://github.com/guyemerson/postgraphql/commit/abbc8006719869e338f113277bcf3ea53443b086. That change looks good, although we may want to change the variable name.

**Comment by calebmer** [comment]
Released in 3.1.0 🎉
