### ISSUE TITLE
Returning void in Postgres function leads to returned property 'string' in GraphQL

### ISSUE THREAD

**Issue by EyMaddis** [postgraphql/postgraphql#429]
Hi,
when creating a function in Postgres that returns void (it either works or throws an exception), the payload type of the mutation will have a property `string` which is always empty.

**Comment by calebmer** [comment]
Thanks for bringing this to our attention. This should be fixed by: https://github.com/postgraphql/postgraphql/pull/435

In the current implementation procedures that would be GraphQL queries that return void throw an error. What do you think about this behavior? Perhaps instead of throwing an error we should simply silently ignore those procedures.
