### ISSUE TITLE
JWT not working at all

### ISSUE THREAD

**Issue by avraamisvi** [postgraphql/postgraphql#447]
Hi there, I have tried to use jwt in postgraphql, but it is simple not working. It is behaving as if it is not defined. I have used the following command:

`postgraphql --jwt-secret mypassword -c postgresql://localhost:5432/ContentManagement --watch`

But as I have said it behave as if I had not specified this, it is not requiring a token to be passed. Is not this a bug?

**Comment by benjie** [comment]
Using the token passes information through to PostgreSQL via config variables (and changing the role). Not passing a JWT just uses the default settings. If you want to protect your schema from access when a JWT token is not specified you should revoke access to the default role and add a role that is granted by the JWT token.

Please read the PG JWT spec here:

https://github.com/postgraphql/postgraphql/blob/master/docs/pg-jwt-spec.md

Also note `mypassword` shouldn't really be a password - it's a secret so a decently long random string of characters that no-one except your server needs to know. Changing it will revoke all existing sessions (by breaking the signature validation) but will otherwise do no harm.

**Comment by avraamisvi** [comment]
Thank you @benjie for your response, but I could not understand how to enable the JWT token. The documentation is not clear for me. It is necessary to create some configuration in postgresq? What I really need to do to be able then to use the jwt? Maybe the documentation should be improved.

**Comment by benjie** [comment]
The JWT specification is detailed here: https://jwt.io/ ; you can use the debugger to see if you've encoded your JWT token correctly. The token is passed via the `Authorization` header as a `Bearer` token, e.g.:

```
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
```

As per [our PG JWT spec](https://github.com/postgraphql/postgraphql/blob/master/docs/pg-jwt-spec.md) we use the "role" attribute on the JWT object to specify which postgresql "role" (ref: CREATE ROLE) to use whilst performing the SQL queries.

If you're still stuck, please specify in detail what you are doing and we may be able to spot what is going wrong.

Please try and remember where you are getting confused/stuck so that once you're up and running you can help us improve the documentation - pull requests are welcome!

Good luck!

**Comment by avraamisvi** [comment]
Thank you again @benjie I think I found the answer looking at the examples, mainly the forum_example.

Thanks
