### ISSUE TITLE
Deprecated fields

### ISSUE THREAD

**Issue by danielbuechele** [postgraphql/postgraphql#473]
I did not see a way to mark fields as deprecated. However, GraphQL allows this, I think. My idea would be to use the column comments for this. We could introduce a `@deprecated` flag, that will be stripped from the description shown in GraphiQL.

**Comment by benjie** [comment]
This sounds like a reasonable request. Let's add a few extra caveats:

- tags match the regexp `/@[a-z]+/` and either be followed by a space or the end of the string
- tags must appear at the very beginning of the comment
- multiple tags should be separated by a single space
- if a tag is not supported, it should still be removed from the comment but a warning should be emitted
- to pass a string through without tags being passed, simply prefix it with a space.

e.g. (spaces replaced with `·` because GitHub swallows some whitespace)

- `@deprecated·The·person's·name`
  - tags: deprecated
  - text: `The·person's·name`
- `@foo·@bar·Baz`
  - tags: foo, bar
  - text: `Baz`
- `·@foo·@bar·Baz` (note: prefixed with a space -> pass through)
  - tags: -
  - text: `@foo·@bar·Baz`
- `@foo··@bar·Baz` (note the double space between `@foo` and `@bar`)
  - tags: foo
  - text: `@bar·Baz`
- `@foo@bar·Baz`
  - tags: -
  - text: `@foo@bar·Baz`
- `Blah·blah·@deprecated`
  - tags: -
  - text: `Blah·blah·@deprecated`

I'd be happy to see a PR that implemented this, with the above as a test suite.

**Comment by benjie** [comment]
This would make an excellent plugin for PostGraphQL v4

**Comment by DealerUplift-DavidJohnston** [comment]
In theory it would be nice to accommodate multi-line comments and treat each line according to those rules.

**Comment by danielbuechele** [comment]
I started looking into this and already created the test suite. However, then I realized that GraphQL switched from `isDeprecated: boolean` to `deprecationReason: string`. This means we need to modify the way this works a little. I like the @benjie's suggestion to make this a more general logic for arbitrary tags.
What about this:
- `The person's name @deprecated Persons now have first and last name`.
  - tags: `Map<string, string> = {deprecated: 'Persons now have first and last name'}`
  - text: `The person's name`
- `The person's age @deprecated use birthdate instead @otherTag`
  - tags: `Map<string, string> = {deprecated: 'use birthdate instead', otherTag: ''}`
  - text: `The person's age`

**Comment by benjie** [comment]
@DealerUplift-DavidJohnston's idea of multi-line comments seems like a good idea; it's a little bit like decorators:

```
@deprecated Persons now have first and last name
@foo
@author Twitter: @foobar
@notes Email foo@example.com if you get stuck with this
The person's full name.
```

The advantage of this is that tags can then contain `@` symbols - they're more of a "meta" system which I think is more powerful. It's also possible then to have "comments" within the comments by prefixing with e.g. `@@`.

**Comment by benjie** [comment]
@danielbuechele I'd love to tweak the test suite you've written to work with a version based on `\n` newlines in comments.

**Comment by danielbuechele** [comment]
You can find it here: https://github.com/danielbuechele/postgraphql/commit/d720ec9ae6827b55ee99442260203e38bc9ddaaf

**Comment by benjie** [comment]
Sent you a PR:

https://github.com/danielbuechele/postgraphql/pull/1/files

The new rules are:

- comments are split on linefeed (newline) characters (`\n`) - dealing with `\r\n` is optional
- tag processing starts at the beginning and looks for lines beginning with `@`; once a line doesn't begin with an `@` tag processing stops.
- tags match the regexp `/@[a-z]+/` and either be followed by a space, newline or the end of the string
- private comments may be added using the special tag `@@` (which also must followed by a space, newline or the end of the string)
- if you want your comment to start with an `@` preceded by any number of spaces, prefix it with an additional space (` @` -> `@`; `     @` -> `    @`)
- tags may have a payload which is the rest of the line after the space
- tags without a payload have implicit value `true`
- tags *may* have an empty payload, giving them value `''` (empty string)

e.g. (some spaces replaced with `·` because GitHub swallows some whitespace)

- `@deprecated Persons now have first and last name\n·The·person's·name`
  - tags: `{deprecated: "Persons now have first and last name"}`
  - text: `The·person's·name`
- `@foo\n@bar\nBaz`
  - tags: `{foo: true, bar: true}`
  - text: `Baz`
- `·@foo\n@bar\nBaz` (note: prefixed with a space -> pass through; line started with non-@: stop processing)
  - tags: `{}`
  - text: `@foo\n@bar\nBaz`
- `@foo\n·@bar\nBaz` (note the space before `@bar`)
  - tags: `{foo: true}`
  - text: `@bar\nBaz`
- `@foo@bar·Baz`
  - tags: `{}`
  - text: `@foo@bar·Baz`
- `Blah·blah·@deprecated`
  - tags: `{}`
  - text: `Blah·blah·@deprecated`

**Comment by mattbretl** [comment]
I created a [v4 branch](https://github.com/mattbretl/graphile-build/tree/deprecate-from-comment) which includes a tag parser (passing @benjie's test spec above) and a plugin to deprecate the fields in GraphQL.   

The [plugin](https://github.com/mattbretl/graphile-build/blob/7fcdf8b1ffbaae411a01221f0c223d35f72dc319/packages/graphile-build/src/plugins/DeprecateFromCommentPlugin.js) is admittedly a bit of a hack..  it strips all tags from the GraphQL field descriptions, and if it finds a `@deprecated` tag, it marks the field as deprecated in GraphQL.  Since this whole tags-embedded-in-column-comments approach is PG specific, this should probably be written as a PG introspection-based plugin instead of tacking it on at the end.  @benjie wants to do some refactoring of PgColumnsPlugin.js first, and then I'll take another shot at this.

**Comment by benjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ensure all `fieldWithHooks` calls declare the correct data on the third argument (scope)](https://trello.com/c/2A5QkxU8/13-ensure-all-fieldwithhooks-calls-declare-the-correct-data-on-the-third-argument-scope)

**Comment by benjie** [comment]
I'd like magic comments in v4, so I've added this to the v4 release list. As stated, I need to refactor PgColumnsPlugin.js first

**Comment by benjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#473 - magic comments / deprecate fields](https://trello.com/c/Cv1bxDeG/19-473-magic-comments-deprecate-fields)

**Comment by benjie** [comment]
So now you can do a check something like:

```
if (pgIntrospection && pgFieldIntrospection && pgIntrospection.type === 'class' && pgFieldIntrospection.type === 'attribute') {
  const commentFromPg = pgFieldIntrospection.description;
  // Process comment here...
}
```

Would be nice to have this same feature on other things too - computed fields, query procedures, mutation procedures, etc.

**Comment by benjie** [comment]
This is implemented

```sql
comment on column tablename.columnname is E'@deprecated Deprecation reason\nGraphQL comment';
```
