### ISSUE TITLE
Workflows for administrative tasks?

### ISSUE THREAD

**Issue by matthewmueller** [postgraphql/postgraphql#488]
I was wondering if you have any workflows / solutions for handling administrative tasks. From my experience with tokens and row-level security, it's pretty annoying to do common administrative tasks like de-activate a user.

Do you setup the JWT roles in a particular way or use conditionals in the RLS to say, this role or this role can access this resource?

**Comment by benjie** [comment]
Yes, I do.

So here's how I set up my roles:

```sql
CREATE ROLE appname WITH LOGIN PASSWORD '${GENERATED_PASSWORD}';
CREATE ROLE appname_authenticator WITH LOGIN PASSWORD '${GENERATED_PASSWORD2}' NOINHERIT;
CREATE ROLE appname_visitor;
CREATE ROLE appname_admin WITH INHERIT;
GRANT appname_visitor TO appname_admin;
GRANT appname_visitor TO appname_authenticator;
GRANT appname_admin TO appname_authenticator;

DO \$\$
BEGIN
  EXECUTE 'GRANT appname TO ' || user;
  EXECUTE 'GRANT appname_authenticator TO ' || user;
END;
\$\$ LANGUAGE PLPGSQL;

CREATE DATABASE $DB_NAME OWNER appname;
REVOKE ALL ON DATABASE $DB_NAME FROM PUBLIC;
GRANT CONNECT ON DATABASE $DB_NAME TO appname;
GRANT CONNECT ON DATABASE $DB_NAME TO appname_authenticator;
GRANT ALL ON DATABASE $DB_NAME TO appname;
```

Then I modify the JWT role based on whether or not the user is an admin (appname_admin) or not (appname_visitor). I also set a JWT claim for admin for when `security definer` is used somewhere (since that effectively changes the role) so I can use a `current_user_is_admin()` method in my DB logic.

When creating my grants and RLS policies I can grant additional policies to specifically the appname_admin role.

One potential issue with this way is that all the admin behaviours come through to the GraphQL schema, so although they cannot be used by non-admins they can be discovered. A potential solution to this is to have two PostGraphQL schemas and use a different endpoint for admins (or, alternatively, to switch the schema that is in use based on the JWT).

Hope this helps.

**Comment by benjie** [comment]
(Authenticator is the default role that PostGraphQL assumes, I grant that role only enough permissions to introspect the schema and no more, plus of course the ability to switch to one of the relevant roles based on the JWT)

**Comment by matthewmueller** [comment]
@benjie thanks for the excellent response! I'm going to give this a second go with separate logins. 

The basic issue I ran into was not being able to change/delete things easily when I was using PSQL while using RLS. I would always have to change roles, which isn't terrible, but gets annoying over time. I'd like for my RLS conditions to understand that if I'm able to log in with a certain user, I can act on the data unconditionally.

**Comment by ansarizafar** [comment]
Could you please further explain following points with an example.

> Then I modify the JWT role based on whether or not the user is an admin (appname_admin) or not (appname_visitor). I also set a JWT claim for admin for when security definer is used somewhere (since that effectively changes the role) so I can use a current_user_is_admin() method in my DB logic.

> (Authenticator is the default role that PostGraphQL assumes, I grant that role only enough permissions to introspect the schema and no more, plus of course the ability to switch to one of the relevant roles based on the JWT)

**Comment by benjie** [comment]
Raise it as an issue against graphile.github.io repo and I’ll write an article about it at some point.
