### ISSUE TITLE
Graphql EndPoint Authentication

### ISSUE THREAD

**Issue by SeenaLibin** [postgraphql/postgraphql#519]
Hi,
I am using the concept JWT authentication in postgraphql. I have generated JWT token following the steps explained in [https://github.com/postgraphql/postgraphql/blob/master/examples/forum/TUTORIAL.md#json-web-tokens](url). I called current_user function and it returns correct result. But my problem is that others queries and mutations are not authenticated. If I am calling /graphql endpoint without Authorization header i am getting results for queries. Why the entire endpoint is not authenticated?Is it due to any mistake from my side?

**Comment by benjie** [comment]
Hi @SeenaLibin; you need to utilise the security features of the database, such as GRANTs and Row Level Security (RLS), so that tables and functions are protected using the credentials granted by JWT.

Have a look at the forum example, particularly:

https://github.com/postgraphql/postgraphql/blob/master/examples/forum/TUTORIAL.md#grants
https://github.com/postgraphql/postgraphql/blob/master/examples/forum/TUTORIAL.md#row-level-security

**Comment by SeenaLibin** [comment]
Hi @benjie 
Thanks for your support. One more doubt. Can I make the endpoint authorized without using RLS?

**Comment by benjie** [comment]
Yes, you can use just `GRANT` and then make sure that each user has their own database user (role), and make sure that that user account is specified in the JWT token `role` field and that that role is granted (with `NOINHERIT`) to your connection user; but it's a lot more work to encode your permission logic with GRANT than it is to do it with RLS; you'd need to define access functions and mutation functions to do everything and don't make any of the non-public tables available in your schema by default and a bunch of other precautions.

If you're asking for a way of controlling the access level at a different tier than inside your database then currently the answer to that is "no" because there is no way in PostGraphQL for you to specify those permission constraints other than to do it in the database itself. I highly recommend you embrace RLS, it will make your database much more secure.

**Comment by SeenaLibin** [comment]
@benjie 
Thanks a lot...  :+1:
