### ISSUE TITLE
how to create with serial primary key

### ISSUE THREAD

**Issue by jmparsons** [postgraphql/postgraphql#538]
I'm trying to do the most simple create mutation.

```js
mutation ($user:UserInput!) {
  createUser(input: {user:$user}) {
    user{
      id
      name
    }
  }
}
```
variables:
```js
{"user": {"id": 1, "name": "John" }}
```
How can I omit the id field?
```js
{"user": {"name": "John" }}
```
schema:
```sql
create table mydb.user (
  id              serial not null primary key,
  name            text not null
);
```

**Comment by benjie** [comment]
@jmparsons If you've marked `id` as `primary key` and it has a default then you shouldn't need to specify `id`; if you're still struggling please provide your database schema (or at least the user table) and we'll try to help 👍

**Comment by jmparsons** [comment]
@benjie Hi I've updated my question with the schema. It's just two fields id and name.

**Comment by benjie** [comment]
@jmparsons You should be able to just omit the `id`... is it that you've set the variables to `client` instead of `user`?

If you look in GraphiQL you should see something like this:

![screenshot 2017-08-02 00 24 17](https://user-images.githubusercontent.com/129910/28851200-ee48e65a-7718-11e7-97de-7e98efeb9f36.png)

The `id: Int` has no exclamation mark so is not required.

**Comment by jmparsons** [comment]
@benjie If I omit I get: `"duplicate key value violates unique constraint \"user_pkey\""`

**Comment by jmparsons** [comment]
@benjie I got it to work, but I had to wipe my data. I have a data seed and the increment tries to use a key that's already be applied giving me `"duplicate key value violates unique constraint \"user_pkey\""`.

I guess is there a way to update the postgres cursor or something along those lines for seeded data?

**Comment by benjie** [comment]
That's entirely a PostgreSQL concern; you'd have the same issue on the command line with `psql`

(But since you asked: you're looking for the [`ALTER SEQUENCE`](https://www.postgresql.org/docs/9.6/static/sql-altersequence.html) command)

To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.

**Comment by jmparsons** [comment]
@benjie You're the best!
