### ISSUE TITLE
Grant select certain columns caused permission denied

### ISSUE THREAD

**Issue by amizz** [postgraphql/postgraphql#549]
Permission denied only occur when I'm using graphql. Running select on psql doesn't give errors.

Table:
```sql
create table public.account(
  id serial primary key,
  email text not null,
  password text,
  created_at timestamp default now()
);
insert into public.account(email, password) values('test@testemail.com', '1234566');
```

Grant:
```sql
create role account_user;
grant select(id, email) on table public.account to account_user;
```

Run postgraphsql:
```bash
DEBUG="postgraphql:*" postgraphql -c "postgres://postgres:postgres@localhost:5432/rls_test" -s public -r account_user
```

GraphQL:
```javascript
query {
    allAccounts {
        nodes {
            id
            email
        }
    }
}
```
Result:
```json
{
  "errors": [
    {
      "message": "permission denied for relation account",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allAccounts"
      ]
    }
  ],
  "data": {
    "allAccounts": null
  }
}
```
CLI Error:
```bash
Mon, 14 Aug 2017 06:54:07 GMT postgraphql:request GraphQL query request has begun.
Mon, 14 Aug 2017 06:54:07 GMT postgraphql:request GraphQL query is parsed.
Mon, 14 Aug 2017 06:54:07 GMT postgraphql:request GraphQL query is validated.
Mon, 14 Aug 2017 06:54:07 GMT postgraphql:graphql { allAccounts { nodes { id } } }
Mon, 14 Aug 2017 06:54:07 GMT postgraphql:postgres begin
Mon, 14 Aug 2017 06:54:07 GMT postgraphql:postgres select set_config($1, $2, true)
Mon, 14 Aug 2017 06:54:07 GMT postgraphql:postgres with __local_0__ as ( select __local_1__ as value from "public"."account" as __local_1__ where "id" is not null and true and true and true order by "id" using < limit all ) select to_json(__local_0__.value) as value from __local_0__;
Mon, 14 Aug 2017 06:54:07 GMT postgraphql:postgres:error error: permission denied for relation account
    at Connection.parseE (C:\Users\Amizz\AppData\Roaming\nvm\v8.2.1\node_modules\postgraphql\node_modules\pg\lib\connection.js:567:11)
    at Connection.parseMessage (C:\Users\Amizz\AppData\Roaming\nvm\v8.2.1\node_modules\postgraphql\node_modules\pg\lib\connection.js:391:17)
    at Socket.<anonymous> (C:\Users\Amizz\AppData\Roaming\nvm\v8.2.1\node_modules\postgraphql\node_modules\pg\lib\connection.js:129:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)
Mon, 14 Aug 2017 06:54:07 GMT postgraphql:postgres commit
Mon, 14 Aug 2017 06:54:07 GMT postgraphql:request GraphQL query has been executed.
Mon, 14 Aug 2017 06:54:07 GMT postgraphql:request GraphQL query request finished.
1 error(s) as account_user in 90.67ms :: { allAccounts { nodes { id } } }

```

Query 1 using psql;
```sql
set role account_user
select id, email from account;
```
Result:
```bash
 id |       email
----+--------------------
  1 | test@testemail.com
```

Query 2 using psql:
```sql
set role account_user
select id,email,password from account;
````
Result:
```bash
ERROR:  permission denied for relation account
```

**Comment by benjie** [comment]
PostGraphQL v3 selects all columns due to how it works- this is required for computed columns to work in that ststem.

PostGraphQL v4 is a ground-up rewrite which hopefully resolves this issue (and gives a decent performance boost as well) by only requesting the required fields. I suggest you try the alpha via `npm install -g postgraphql@next` (see #506)

**Comment by amizz** [comment]
Thanks for the fast reply. Is there any major breaking changes when upgrading from v3 to v4?

**Comment by benjie** [comment]
I keep the breaking changes list in #506 up to date; it should mostly be a drop-in replacement. It's still an alpha so there are probably still issues to be discovered.

**Comment by benjie** [comment]
@amizz Please let me know if you have any issues with this; I've not actually tried selective grants myself (and we don't have any tests for them).

**Comment by amizz** [comment]
Grants with column selected seems to work using v4. Will update if anything comes up. Thanks.

SQL reference example:
```sql
grant select("id", "name") on table public.person to anonymous;
grant select("id", "name", "age") on table public.person to super_user, postgraphql;
```

GraphQL Query:
```javascript
query {
	allPersons {
		nodes {
			id
			name
		}
	}
}
```

**Comment by flux627** [comment]
If the role Postgraphile has when creating the schema has limited column access on a table, would it make sense to not include those columns in the schema?

Or, what is the recommended way to exclude columns from the schema?

**Comment by benjie** [comment]
This is something that needs work.

pgColumnFilter exists but is undocumented currently; that’s the currently advised way (but hopefully it’ll be better in future)

**Comment by flux627** [comment]
How do I use it? (Suggesting to use something without explaining how, while simultaneously acknowledging that it's not documented, is a bit humorous ;)

**Comment by benjie** [comment]
Yeah, I was in bed on mobile so thought it might be enough for you to search the code if you were in a rush.

It was introduced here:

https://github.com/graphile/graphile-build/pull/73

Basically you pass it into the library version via graphileBuildOptions because we’ve not exposed it via the CLI yet (it’s undocumented and experimental), it’s a function that takes three arguments to decide whether or not to add the column to the schema. The args are:

- attr which is the attribute data from the introspection query, you probably care most about ‘name’ and ‘class.name’ for global filtering
- build - a build object, see the graphile-build docs
- context - the context (see graphile-build docs) - this is useful for hiding a column for inserts but not for selects, for example.

It would be great if

**Comment by flux627** [comment]
Thanks Benji, I really appreciate it. I think my attempt at playfulness simply came off as passive aggression, so I do apologize. For what it's worth, I did try searching the codebase, but didn't turn up with anything useful. I didn't realize that I needed to be searching in another repository.

My use-case was to simply omit private columns that begin with `_` (except for `_id`). Here's the code I ended up with that worked:

```javascript
const express = require("express")
const http = require("http")
const dbConfig = require("../config/db")
const postgraphileConfig = require("../config/postgraphile")
const { postgraphile } = require('postgraphile')
const postGraphilePlugins = require("../src/postGraphilePlugins")

// Attach plugins tp Postgraphile config
postgraphileConfig.appendPlugins = postGraphilePlugins

// Attach graphileBuildOptions to config
postgraphileConfig.graphileBuildOptions = {
  pgColumnFilter: (attr) => {
    // TODO: Figure out how to filter tables; commented code below causes errors
    // if (attr.class.name[0] === "_") return false
    if (attr.name[0] === "_" && attr.name !== "_id") return false
    return true
  }
}

// Instantiate express server with Postgraphile
const app = express()
app.use(
  postgraphile(dbConfig, dbConfig.schema, postgraphileConfig)
)
const server = http.createServer(app)
```

On a related note, is there any way to omit tables entirely? I know the documentation says to put private tables into a different schema, but this is organizationally not ideal for my project.

**Comment by benjie** [comment]
Not right now, but you can acheive it via plugins (just drop the relevant fields) though I wouldn’t recommend that in the long term.

I’m planning to add a bunch of smart comments to the system - e.g. you could add “@exclude” to the comment for a table and it’d be excluded automatically - would this work for you? I don’t like managing this via config because I fear if you rename the table its exclusion may no longer trigger. I’d also prefer PostgreSQL as the single source of truth.

**Comment by flux627** [comment]
That sounds like a reasonable solution. I'm assuming these kind of smart comments would be one per line, and would be trimmed off when the comment is used for documentation? Or maybe an explicit `@description` tag could optionally be used.

I've also been tracking this feature for use on indexing JSONB columns, so I'm pretty excited about smart comments in general. A way to extend functionality with custom smart comments in the same way you can add graphile plugins would be fantastic, and likely a more intuitive way to do many things currently only possible through the graphile plugin interface (from what I can tell so far).

**Comment by benjie** [comment]
Yeah, that’s what I’m thinking 👍

We already have them, I just need to add support for naming tables/skipping things/permissions/etc

**Comment by johnchristopherjones** [comment]
@benjie Do these changes handle `@skip` and `@include` directives?

As of `4.0.0-alpha2.20`, if you try to omit a property from a query with a `@skip` or `@include` where that property is calculated and the function requires different permission, that query still fails even though the problematic field shouldn't be part of the returned result.

That's kind of a mouthful.  What I mean is that if you try to run a query like this for both cases:

```graphql
query Articles($signedIn: Boolean!) {
  allArticles {
    nodes {
      id name article
      isBookmarked @include(if: $signedIn)
    }
  }
}
```

The query will fail if @signedIn is false if that property is satisfied by a function like this:

```sql
create function article_is_bookmarked(article) returns boolean as $$
select exists(select 1 from bookmarks b where b.article_id = article.id);
$$ language sql stable;
```

… and anonymous users don't have access to both execute this function and select from bookmarks.

It should probably succeed because the result only includes things the user has access to.

Fleshing out some of this minimal schema for reference.  In practice you'd be using RLS, but I don't think it's relevant to this problem.

```
create table article(
  id uuid,
  name text,
  content text
);
grant select on article to blog_user, blog_anonymous;

create table bookmarks(
   user_id uuid,
   article_id uuid
);
grant select, insert, delete on bookmarks to blog_user;


create function article_is_bookmarked(article article)
        returns boolean as $$
  select exists(select 1 from bookmarks b where b.article_id = article.id);
$$ language sql stable;
grant execute on article_is_bookmarked(article) to blog_user;
```

You can totally work around this by not relying on the directive in the query, but granting execute on the function and branching in the function based on authorization, but this is probably one kind of thing you want directives for.

**Comment by benjie** [comment]
Huh; you’re right- our planner ignores that directive when building the SQL query. That’s going to be “fun” to resolve. Please can you file it as a new issue, it’s hard to track at the bottom of a closed thread...

**Comment by benjie** [comment]
Fixed in https://github.com/graphile/graphile-build/pull/201

**Comment by benjie** [comment]
Also on the smart comments front; check out: https://github.com/graphile/graphile-build/pull/199
