### ISSUE TITLE
postgraphql production ready? v4.0 release date?

### ISSUE THREAD

**Issue by brandonwoo** [postgraphql/postgraphql#610]
I am considering using postgraphql for a new project. May I know what is the estimated production ready date of v4.0?
Also, are there any projects in production using postgraphql v3 or v4 right now? Could not find information on projects using postgraphql in an actual production environment.

**Comment by benjie** [comment]
The [survey](https://benjie10.typeform.com/to/ALL9df) is still open (hint hint!), but preliminary results (out of 40 responses) suggest there are at least 13 companies using PostGraphQL in production (all but one of whom mount it as an express middleware, and all but 1 of whom have fewer than 10 software developers). I'm also working with a few companies who will have PostGraphQL in production soon.

I do not have an estimated production ready date for v4, we're still working out the kinks. We'll keep developing it until there are no major issues remaining and then we'll upgrade it to beta status. If that goes well we'll make an RC and if that has no issues we'll release v4. If you use persisted queries (as a query whitelist) then so long as you have sufficient tests in place you should be fairly safe running it now.

If you want to accelerate the development of PostGraphQL one way is to [donate](https://www.paypal.me/benjie) 🙏 ; another is to add more [integration tests](https://github.com/graphile/graphile-build/tree/master/packages/postgraphile-core/__tests__/integration) to postgraphile-core. Due to the rebuild we had to throw out all the old tests (except the integration tests) because the entire core is implemented in a completely different way now, so more integration tests will allow us to be more confident about what we're releasing. Have a look through [the existing fixtures](https://github.com/graphile/graphile-build/tree/master/packages/postgraphile-core/__tests__/fixtures) and add more fields (or even entire new fixture files if you like!) for things that aren't currently tested then send a PR. If the tests already pass they'll probably get merged quite quickly; if they fail then it at least gives me a leg up on finding out what's wrong.
