### ISSUE TITLE
GraphiQL auto completion failures with v3.5.1

### ISSUE THREAD

**Issue by ThomasWeiser** [postgraphql/postgraphql#615]
GraphiQL's automatic completion (with ctrl-space) doesn't work on all edit-locations of a query.

Example, assuming a table `document`:
```graphql
query {
  allDocuments {
    nodes {
      id
    }
  }
```
Completion fails e.g. at `id`, while it still works on the outer nesting levels.

It worked flawlessly in v3.5.0 (as well as it does in v4.0.0-alpha2.22).

**Comment by benjie** [comment]
I can reproduce this with a clean checkout, for me it will complete the `allFoos` and the `edges` under it, but not `node` or anything under `node`.

I'm assuming this is because v3 doesn't use a lockfile whereas v4 does and thus a minor update to one of the libraries has caused problems.

I don't have time to look into this, but if you want to do so:

```
npm install
npm run dev -- -c postgres://localhost/YOUR_DB_HERE --schema YOUR_SCHEMA_HERE
```

^ This should get you up and running with the local dev version. Then figure out what's changed (which piece of software has been updated in v3 that hasn't in v4 that could be causing this issue) and once tracked down tweak the version range in package.json to omit the faulty install.

Good luck! 👍

**Comment by benjie** [comment]
(Note `npm run dev` adds a lot of default stuff to your command line, you may want to modify the `--exec` line in `scripts/dev` locally)

**Comment by ThomasWeiser** [comment]
Benjie, thanks for your assistance! Found that the bug results from multiple versions of package `graphql` pulled in.

```
invariant.js:19 Uncaught Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
    at invariant (invariant.js:19)
    at validate (validate.js:60)
    at validateWithCustomRules (validateWithCustomRules.js:29)
    at getDiagnostics (getDiagnostics.js:61)
    at lint.js:43
    at startLinting (lint.js:151)
    at lint.js:199
```

It's probably related to [this pending change](https://github.com/graphql/codemirror-graphql/pull/235) in `graphql/codemirror-graphql`.

I tried to fix this in #616 / #617.

**Comment by benjie** [comment]
Thanks for figuring this out; I’ll take a look tomorrow if I get a chance 👍

**Comment by benjie** [comment]
We're currently waiting on codemirror-graphql to publish 0.6.12, that should hopefully fix it?

https://github.com/graphql/codemirror-graphql/issues/240

**Comment by benjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix GraphiQL auto-completion issues](https://trello.com/c/aGDDZly4/3-fix-graphiql-auto-completion-issues)

**Comment by benjie** [comment]
This is now published 🎉

**Comment by benjie** [comment]
`postgraphql@3.5.4` fixes this 👍

**Comment by benjie** [comment]
(also `postgraphql@4.0.0-alpha2.25`)
