### ISSUE TITLE
Table & Replace function yields "Error: Schema must contain unique named"

### ISSUE THREAD

**Issue by dmattsson** [postgraphql/postgraphql#619]
I have a table and a function to replace all values of a project within the table. Code below. When trying to get postgraphql started for this I get this error: Error: Schema must contain unique named types but contains multiple types named "RevenueYear".

Am I doing something wrong or is this a bug? Any feedback greatly appreciated

```sql
create table vb.revenue_year (
  id               uuid primary key default vb_private.uuid_generate_v1mc(),
  project_id        uuid not null references vb.project(id),
  year              smallint,
  revenue           real, -- 6 digits precision
  revenue_target    real
);
```

```sql
CREATE FUNCTION
  vb.revenue_year_replace_all(project_id uuid, input vb.revenue_year[])
RETURNS vb.revenue_year[]
    LANGUAGE plpgsql
    AS $_$
DECLARE
	ret vb."revenue_year"[];
BEGIN
  DELETE FROM vb."revenue_year" where project_id = $1;
  INSERT INTO vb."revenue_year"
      (project_id, "year", revenue, revenue_target)
      SELECT
      (a)."project_id",
      (a)."year",
      (a)."revenue",
      (a)."revenue_target"
      FROM (SELECT unnest($2) AS a) x WHERE (a)."project_id" = $1
      returning * into ret;
    RETURN ret;
END;
$_$;

grant execute on function vb.revenue_year_replace_all(uuid, vb.revenue_year[]) to vb_person;
```

**Comment by benjie** [comment]
So that error means that two things are boiling down to the same name: "RevenueYear". Without your whole schema I can't tell you what they are but look for things named:

- revenue_year
- revenue_years
- "revenueYear"
- "revenueYears"
- "RevenueYear"
- "RevenueYears"
- etc

Likely there is more than one of them, and the conversion of them to GraphQL is causing a clash.

What version of PostGraphQL are you using?

**Comment by dmattsson** [comment]
I use version 3.2.0.

When I drop the function it works (keep the table) it works, so it seems related to the function I posted above.

PS) (I corrected a slight error in my post - it said create table vb.project_revenue_year, not create table vb.revenue_year)

**Comment by benjie** [comment]
So that function references `vb.revenue_year` (both in the argument list and the return type); is that table already exposed?

Ooo, I wonder if it's because it's an array - do you use `vb.revenue_year[]` anywhere else? We've recently squashed a whole load of array-of-compound-types bugs in v4 - maybe give that a try? `npm install -g postgraphql@next` (see #506 for breaking changes).

**Comment by dmattsson** [comment]
I tried to upgrade to v4 and it solved the problem. Thanks a lot @benjie!
