### ISSUE TITLE
Empty arrays are returned as null

### ISSUE THREAD

**Issue by jgj** [postgraphql/postgraphql#648]
I'm submitting a ... 
- [x] bug report
- [ ] feature request
- [ ] question 

PostGraphQL version:

4.0.0-alpha2.26

Minimal SQL file that can be loaded into a clean database:
``` sql
create table person (
    id          serial primary key,
    name        text not null,
    aliases     text[] not null default '{}'
);

insert into person ( name ) values ( 'test' );
```

Steps to reproduce:

Using the Library as an express middleware

Current behavior:
Empty arrays in postgres cause the error `Error: Cannot return null for non-nullable field Person.aliases` when querying for Person types, e.g.
```
{
  allPersons {
    nodes {
      id
      name
      aliases
    }
  }
}
```
Expected behavior:
No error is thrown and the empty array is returned

**Comment by benjie** [comment]
Good catch, thanks. If you fancy writing a failing test for this, that would be a welcome headstart to getting it fixed! 

Add `aliases` column to one of the tables here:

https://github.com/graphile/graphile-build/blob/master/packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

And add a GraphQL query that triggers the issue here:

https://github.com/graphile/graphile-build/tree/master/packages/postgraphile-core/__tests__/fixtures/queries

**Comment by jgj** [comment]
sure thing, hope this is helpful: https://github.com/graphile/graphile-build/pull/129

**Comment by benjie** [comment]
Perfect; thanks!

**Comment by benjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Empty arrays bug](https://trello.com/c/kPPKRlYM/22-empty-arrays-bug)
