### ISSUE TITLE
Data discrepancy between DB and GraphiQL interface

### ISSUE THREAD

**Issue by Tritpi** [postgraphql/postgraphql#678]
The decimal number data getting displayed in the GraphiQL interface is getting rounded off and hence is different from the data in the DB.

For eg:- If there is a column with value as 1234567899517.1299 in the DB , the same column gets displayed in the GraphiQL interface as 1234567899517.13. 

Is there a way to maintain the data consistency between the DB and the GraphiQL Ui interface.

**Comment by benjie** [comment]
Looks like you might be using standard floats - PostgreSQL is rounding it:

```sql
select 1234567899517.1299::float;

      float8
------------------
 1234567899517.13
```

If you need higher precision than this you should use `numeric`:

```sql
select 1234567899517.1299::numeric;

      numeric
--------------------
 1234567899517.1299
(1 row)
```

If you're using numeric then you should find that PostGraphile outputs it as a string.

(You didn't mention which version you're using.)

**Comment by Tritpi** [comment]
The version of postgraphql being used is 3.5.0. 

The datatype of the column in the Postgres Database is double precision. 
The value of the column in the database is 4859632598745.6797 and when we query the DB the values returned is 4859632598745.6797. But after querying for the same data via the GraphiQL interface, the value is getting rounded off to 4859632598745.68.

Please confirm if there is some rounding logic in the PostgraphQL API.

The version of PostgresQL DB is 9.5.

**Comment by benjie** [comment]
There is no rounding logic in the PostGraphile v4 API - we use the value direct from PostgreSQL (and if we don't support it, we use the string type instead). Both PostgreSQL and V8 use IEEE Standard 754 for Binary Floating-Point Arithmetic, so the values should be equivalent.

In PostGraphQL v3 it's possible that we are attempting to represent a `numeric` or `decimal` as a float which will result in loss of precision due to IEEE Standard 754. As you've opted to not share any SQL with me I can't tell what data types you're working with.

Here's some things that may help you figure it out:

```
select 4859632598745.6797;
      ?column?
--------------------
 4859632598745.6797
(1 row)
```
^ The above is a numeric (arbitrary precision number) which in v4 we represent with a string because Node.js and GraphQL both don't support arbitrary precision numbers. I'm not sure how v3 handles it - it's possible it casts to a float, and this is what the issue is.

```sql
select 4859632598745.6797::float;
      float8
------------------
 4859632598745.68
(1 row)
```
^ PostgreSQL rounds the number to what you say if you treat the number as a float.

**Comment by alanfairless** [comment]
> There is no rounding logic in the PostGraphile v4 API - we use the value direct from PostgreSQL (and if we don't support it, we use the string type instead).

I suspect something more subtle is happening.  I've noticed similar "rounding" behavior with big integers, similar to the loss of precision I would expect with floating point, even when they are attempted to be handled as strings.  

Here's an easily reproducible example using `4.0.0-alpha2.28`:

```sql
create or replace function static_big_integer() returns setof int8 as $$
    select generate_series(30894622507013190, 30894622507014190);
$$ language sql stable security definer;
comment on function static_big_integer() is 
E'generates 1000 integers between 30894622507013190 and 30894622507014190';
```

```
{
  staticBigInteger {
    edges {
      node
    }
  }
}
```

Result:

```javascript
{
  "data": {
    "staticBigInteger": {
      "edges": [
        {
          "node": "30894622507013190"
        },
        {
          "node": "30894622507013190". <-- should end in 1, not 0
        },
        {
          "node": "30894622507013190". <-- should end in 2, not 0
        },
        {
          "node": "30894622507013190". <-- should end in 3, not 0
        },
        {
          "node": "30894622507013190". <-- should end in 4, not 0
        },
        {
          "node": "30894622507013196". <-- should end in 5, not 6
        },
        {
          "node": "30894622507013196"
        },
        {
          "node": "30894622507013196"
        },
        {
          "node": "30894622507013200"
        },
        {
          "node": "30894622507013200"
        },
```

**Comment by benjie** [comment]
Thanks for the reproducing test case! It turns out that PostgreSQL is generating valid JSON but that Node.js is incapable of parsing said JSON without loss of precision. I just had a read through the [JSON specification](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) and it seems JSON actually puts no limit on the size of numbers (I previously believed that they were limited to IEEE754, like JavaScript) - this is yet another way that JSON differs to JavaScript!

With this test case it should be quite easy to work around the issue; I'll get this fixed before v4 enters beta.

**Comment by benjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix PostgreSQL producing JSON that Node.js cannot handle without loss of precision](https://trello.com/c/UNohcAB3/38-fix-postgresql-producing-json-that-nodejs-cannot-handle-without-loss-of-precision)

**Comment by benjie** [comment]
Here's a JSON parser for JS that enables parsing these large numbers:

https://www.npmjs.com/package/json-bigint

However I think I'm just going to convert them to strings in Postgres and stick to the built in JSON.parse

**Comment by alanfairless** [comment]
> However I think I'm just going to convert them to strings in Postgres and stick to the built in JSON.parse

Thanks for the quick replies, and +1 for asking the database to the work!
